version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db-wordpress:/var/lib/mysql
    networks:
      - backend
  wordpress:
    image: wordpress:6.0.0-apache
    container_name: wordpress
    restart: unless-stopped
    ports:
      - 8080:80 
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp
    volumes:
      - wordpress:/var/www/html
    networks:
      - backend
      - frontend
    depends_on:
      - db
  nginx:
    image: nginx:1.22.0
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./wordpress.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend

volumes:
  db-wordpress:
  wordpress:

networks:
  frontend:
  backend:
