---
- name: Install epel-release for CentOS
  ansible.builtin.yum:
    name: epel-release
    state: latest
  when:
    - ansible_facts['distribution'] == 'CentOS'

- name: Packeges update
  yum:
    name: "*"
    state: latest
  register: yum_updates
  when:
    - ansible_facts['distribution'] == 'CentOS'

- name: Update repo index for Debian
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 432000
  when:
    - ansible_facts['os_family'] == 'Debian'

- name: Packeges update for Debian
  apt:
    name: "*"
    state: latest
  when:
    - ansible_facts['os_family'] == 'Debian'    
...
