Vagrant.configure("2") do |config|
  #-TMS-LESSON22-WEB-SERVER-CENTOS-7---------------------------------------------- 
  config.vm.define "tms-web" do |centos|
    centos.vm.box_check_update = true
    centos.vm.box = "centos/7"
    centos.vm.hostname = 'tms-web'
    centos.vm.box_url = "centos/7"
    centos.vm.network :private_network, ip: "192.168.56.200"

    centos.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--name", "tms-web"]
    end
    #centos.vm.provision "shell", path: "scripts/setup_ssh.sh" # Script used to configure local ssh access to vagrant vm and not required for the task 
    centos.vm.provision "shell", path: "scripts/deploy.sh"
  end
#--------------------------------------------------------------------------------- 
end
