version: '3.9'
services:
  jenkins_master:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    networks:
      - jenkins_network

  jenkins_slave:
    image: jenkins/inbound-agent
    container_name: slave
    restart: unless-stopped
    environment:
      JENKINS_URL: http://jenkins:8080
      JENKINS_SECRET: d373dff05fc54f016754535a0ad26f896d0db79485c2710f61819696b14babfb
      JENKINS_AGENT_NAME: slave
      JENKINS_AGENT_WORKDIR: /home/jenkins/agent
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - project_network

  gitea:
    image: gitea/gitea:1.16.9
    container_name: gitea
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "222:22"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - gitea_data:/data
    networks:
      - jenkins_network


volumes:
  jenkins_server:
  gitea_data:
      
networks:
  jenkins_network:
